-- ============================================================================
-- tab — Supabase schema source map
-- ============================================================================
-- The editable database contract is split into numbered files under:
--   supabase/sql/
--
-- The deployable baseline migration is generated from those files at:
--   supabase/migrations/20260518000000_baseline.sql
--
-- Common commands:
--   ./supabase/scripts/build_schema.sh --check   # verify generated baseline
--   bash supabase/tests/00_sql_assembly.sh       # local static check only
--
-- Production contains real user data. Never rewrite the deployed baseline or
-- apply changes without an approved forward-only migration and rollout plan.
-- This file is intentionally small; do not put schema DDL here.
-- ============================================================================
