#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ANDROID_PROPERTIES="$ROOT_DIR/Apps/TabAndroid/local.properties"

"$ROOT_DIR/supabase/scripts/assert_local_only.sh"
"$ROOT_DIR/supabase/scripts/verify_local.sh"

status_env="$(supabase status -o env --workdir "$ROOT_DIR" 2>/dev/null)"
publishable_line="$(printf '%s\n' "$status_env" | awk -F= '$1 == "PUBLISHABLE_KEY" { print substr($0, index($0, "=") + 1) }')"
publishable_key="${publishable_line%\"}"
publishable_key="${publishable_key#\"}"

if [[ -z "$publishable_key" ]] || [[ "$publishable_key" != sb_publishable_* ]]; then
  echo "[android-local] Refusing: local publishable key was not available." >&2
  exit 1
fi

if [[ "$status_env" == *".supabase.co"* ]]; then
  echo "[android-local] Refusing: Supabase status contained a hosted endpoint." >&2
  exit 1
fi

umask 077
tmp_file="$(mktemp "$ANDROID_PROPERTIES.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

{
  echo "# Generated by supabase/scripts/configure_android_local.sh."
  echo "# Disposable local development configuration. Never commit this file."
  echo "TAB_LOCAL_SUPABASE_URL=http\\://127.0.0.1\\:54321"
  printf 'TAB_LOCAL_SUPABASE_PUBLISHABLE_KEY=%s\n' "$publishable_key"
} > "$tmp_file"

mv "$tmp_file" "$ANDROID_PROPERTIES"
trap - EXIT

echo "[android-local] Wrote ignored Android debug configuration for the local stack."
echo "[android-local] Run supabase/scripts/connect_android_emulator.sh before launching or testing."
